### ISSUE TITLE
2. Random Crash using SDK 2.1.2

### ISSUE THREAD

**Issue by n-ahmad** [Clicktale/android-sdk-demo#2]
**Fatal Exception: java.lang.RuntimeException
setDataSource failed: status = 0x80000000**
	
android.media.MediaMetadataRetriever.setDataSource (MediaMetadataRetriever.java)
android.media.MediaMetadataRetriever.setDataSource (MediaMetadataRetriever.java:70)
android.media.MediaMetadataRetriever.setDataSource (MediaMetadataRetriever.java:159)
com.clicktale.clicktalesdk.l.b.e (SourceFile:105)
com.clicktale.clicktalesdk.l.b.d (SourceFile:98)
com.clicktale.clicktalesdk.l.b.h (SourceFile:90)
com.clicktale.clicktalesdk.l.b.a (SourceFile:76)
com.clicktale.clicktalesdk.CTService.a (SourceFile:131)
com.clicktale.clicktalesdk.CTService.a (SourceFile:25)
com.clicktale.clicktalesdk.CTService$a.handleMessage (SourceFile:150)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.os.HandlerThread.run (HandlerThread.java:61)

![clicktale crash](https://cloud.githubusercontent.com/assets/26374268/25516522/7ef867d0-2c04-11e7-99b0-1a02058dd159.png)

**Comment by daviduzan** [comment]
fixed
